### ISSUE TITLE
请问这个qiao.h.js是干什么的

### ISSUE THREAD

**Issue by weige0088** [uikoo9/dishi#2]
请问这个qiao.h.js是干什么的  ，还有这个qmask  。
你的教程能写详细些吗，或者出个视频的也行！

**Comment by uikoo9** [comment]
h的意思是hibirdapp的意思，就是对mui以及nativejs的一些封装，教程已经很详细了，qmask就是一个遮罩，而且还有源码。

**Comment by weige0088** [comment]
哦谢谢回答，这个框架刚刚学习，但是不知道从哪里入手，公司新的项目马上要用，现在有点头疼！
